services:
  meroottools:
    image: meroottools
    container_name: meroottools
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    environment:
      - NODE_ENV=production